#! /bin/sh

#### AUTOSTART ####
sxhkd &
compton &
#wal -i $HOME/.config/bspwm/Wallpaper/wallpaper.png &
synclient TapButton1=1 TapButton2=3 TapButton3=2 & #For laptop touchpad
#xset -b & #For annoying beeping sounds
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#volumeicon &
#nm-applet &
#pulseaudio &

bspc config border_width         0
bspc config window_gap           15

#bspc config top_padding 22

#Various settings
bspc config click_to_focus button1
bspc config swallow_first_click false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

##Color settings
bspc config focused_border_color "#1ABB9B"
bspc config normal_border_color "#2D2D2D"
#"#000000"
bspc config presel_feedback_color "#1ABB9B"
#"#8F3724"

# Pointer settings
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false

#Settings for manual splitting
bspc config split_ratio         0.52

###This creates and names desktops for multiple monitors.
#workspaces_multimonitor &

bspc rule -a screenkey --unmanage
bspc rule -a gcolor2 state=floating center=true
bspc rule -a lxappearance state=floating center=true
bspc rule -a gmrun state=floating center=true
bspc rule -a viewnior state=floating center=true
bspc rule -a file-roller state=floating center=true
bspc rule -a floaterm state=floating center=true
bspc rule -a file-roller state=pseudo_tiled
bspc rule -a transmission-gtk state=pseudo_tiled
bspc rule -a conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a yad state=floating
bspc rule -a Docky layer=above border=off manage=on
bspc rule -a Plank layer=above border=off manage=on
bspc rule -a wbar layer=above
bspc rule -a dockbarx layer=above
bspc rule -a firefox private=on
bspc rule -a midori private=on
bspc rule -a gnome-pie border=off manage=off
bspc rule -a wpa_gui state=pseudo_tiled
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a 9menu border=off manage=off
bspc rule -a tint2 border=off manage=off

##Edge-switcher switches to next workspace when moves moves to the 
##edge of the monitor (behavior similar to enlightenment)
#edge-switcher &

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window

# Start polybar
#polybar -r example &

bspc monitor HDMI2 -d VI VII VIII IX X
bspc monitor eDP1 -d I II III IV V


for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  MONITOR=$m polybar --reload example &
done